# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia_extend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zinnia_extend.Gallery'),
        ),
    ]
