# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 20:51
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panampath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathsegment',
            name='geom',
            field=djgeojson.fields.MultiLineStringField(),
        ),
    ]
