# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panampath', '0002_auto_20180428_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathsegment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathsegment',
            name='geom',
            field=djgeojson.fields.MultiLineStringField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathsegment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
